name: Salesforce Metadata Deploy
description: Builds and deploys metadata to a specified environment
author: jawills
branding:
  icon: code
  color: blue
inputs:
  DRY_RUN:
    description: "Validate deploy and run Apex tests but don't save to the org."
    type: boolean
  TEST_LEVEL:
    description: "Deployment Apex testing level."
    type: choice
    default: RunLocalTests
    options:
      - NoTestRun
      - RunSpecifiedTests
      - RunLocalTests
      - RunAllTestsInOrg
  WAIT:
    description: "Number of minutes to wait for command to complete and display results."
    type: number
    default: 30
  SOURCE_DIRECTORY:
    description: "Path to the local source files to deploy."
    type: string
    default: force-app
  SFDX_AUTH_URL:
    description: "The auth url tied to your deployment environment"
    type: string
    required: true
  DEPLOYMENT_ID:
    description: "The deployment id from a validation/ dry run."
    type: string

runs:
  using: "composite"
  steps:
    - name: Install Salesforce CLI
      shell: bash
      run: |
        npm install -g @salesforce/cli
        sf --version
    - name: Login to Environment
      shell: bash
      run: |
        sf org login sfdx-url --set-default --sfdx-url-file <(echo "${{ inputs.SFDX_AUTH_URL }}")
    - name: Generate package.xml
      shell: bash
      run: |
        sf project generate manifest --source-dir ${{ inputs.SOURCE_DIRECTORY }} --output-dir manifest
    - name: Start deployment
      shell: bash
      run: |
        deployFlags=(
            --manifest manifest/package.xml
            --wait ${{ inputs.WAIT }}
            --test-level ${{ inputs.TEST_LEVEL }}
            --verbose
            --async
            --json
          )
        if [ "${{ inputs.DRY_RUN }}" = "true" ]; then
          deployFlags+=( --dry-run )
        fi
        if [ -n "${{ inputs.DEPLOYMENT_ID }}" ]; then
          deployFlags+=( --job-id ${{ inputs.DEPLOYMENT_ID }} )
        fi
        sf project deploy start "${deployFlags[@]}" > run.json
        (jq -r '.result.id' run.json) > deployment-id.txt
        cat deployment-id.txt
    - name: Resume Deployment
      shell: bash
      run: |
        echo "::set-output name=deployment-id::$(cat deployment-id.txt)"
        sf project deploy resume -i $(cat deployment-id.txt)
